### ISSUE TITLE
java.lang.RuntimeException: Logical sources are not equal.

### ISSUE THREAD

**Issue by asotona** [carml/carml#18] opened 2017-10-24 12:39 UTC
Hi,
I'm trying to execute parentTriplesMapping.rml.ttl from your test cases.

First issue I found that calling mapper.bindInputStream("parentTriplesTestInput.json", ...)); is not enough to resolve the InputStream as bound to the "parentTriplesTestInput.json" source name.

I've workarounded that issue by slight modification of the parentTriplesTestInput.json to:
<mapping...> rml:source [a carml:Stream ;
    carml:streamName "parentTriplesTestInput.json".]

However after that I get an exception preventing the execution of the Parent/Child mapping:

java.lang.RuntimeException: Logical sources are not equal.
Parent: LogicalSourceImpl [getSource()=CarmlStreamImpl [streamName=rmltest], getIterator()=$.colors.code, getReferenceFormulation()=http://semweb.mmlab.be/ns/ql#JSONPath]
Child: LogicalSourceImpl [getSource()=CarmlStreamImpl [streamName=rmltest], getIterator()=$.colors, getReferenceFormulation()=http://semweb.mmlab.be/ns/ql#JSONPath]
	at com.taxonic.carml.engine.RmlMapper.checkLogicalSource(RmlMapper.java:295)

Thanks for any help,
Adam Sotona

**Comment by pmaria** [comment] 2017-10-24 14:18
Hi Adam,

First off, thanks for trying out CARML!

I'm sorry that you're having trouble with the API. Understandable as well, since our documentation is not yet up to par. We're working on it!

From your description I'm not entirely sure what you want to achieve. I believe you're trying to execute the mapper on the `parentTriplesMapping.rml.ttl` file in the tests as is.

In that case you could do something like:
```java
// Determine base path url string for a classpath resource
String fileName = "parentTriplesMapping.rml.ttl";
File file = new File(TestCarml.class.getResource(fileName).getFile());
// Or just set the basepath if you know it.
// Note that the basepath doesn't have to be set if logical source 
// described in the mapping uses an absolute file path to the source.
String basePathUrl = file.getParent();
System.out.println(basePathUrl);

// Create mapper with specific basepath for logical sources.
Path basePath = Paths.get(basePathUrl);
RmlMapper mapper = RmlMapper.newBuilder().fileResolver(basePath).build();

// Get mapping file from same folder
Set<TriplesMap> mapping =
	RmlMappingLoader
		.build()
		.load(Paths.get(basePathUrl + "/parentTriplesMapping.rml.ttl"), RDFFormat.TURTLE);

// Execute mapping
Model result = mapper.map(mapping);

// Print model
result.forEach(System.out::println);
```

Binding the input stream is not necessary in this case since we're using a file based source. Binding inputstreams is useful when you don't have a file, but some other process has a stream of data it wants to process.

I'll make a note to add some more examples and explanation to the readme about this.

I hope this helps. If I misintepreted your question please let me know.

Cheers,
Pano

**Comment by pmaria** [comment] 2017-10-24 14:30
Another, simpler, example specifiying the specific file location:
```
// Create mapper with specific basepath for logical sources.
Path basePath = Paths.get("D:/folder");
RmlMapper mapper = RmlMapper.newBuilder().fileResolver(basePath).build();

// Get mapping file from same folder
Set<TriplesMap> mapping =
	RmlMappingLoader
		.build()
		.load(Paths.get("D:/folder/parentTriplesMapping.rml.ttl"), RDFFormat.TURTLE);

// Execute mapping
Model result = mapper.map(mapping);

// Print model
result.forEach(System.out::println);
```

**Comment by asotona** [comment] 2017-10-24 20:38
Hi Pano,thanks for the reply, I just need to provide the Json content directly ( as streams or String fragments) without creating intermediate files.
Thank you,Adam
-------- Původní zpráva --------Od: Pano Maria <notifications@github.com> Datum: 24.10.17  16:18  (GMT+01:00) Komu: carml/carml <carml@noreply.github.com> Cc: Adam Sotona <adam.sotona@gmail.com>, Author <author@noreply.github.com> Předmět: Re: [carml/carml] java.lang.RuntimeException: Logical sources are not
  equal. (#18) 
Hi Adam,
First off, thanks for trying out CARML!
I'm sorry that you're having trouble with the API. Understandable as well, since our documentation is not yet up to par. We're working on it!
From your description I'm not entirely sure what you want to achieve. I believe you're trying to execute the mapper on the parentTriplesMapping.rml.ttl file in the tests as is.
In that case you could do something like:
// Determine base path url string for a classpath resource
String fileName = "parentTriplesMapping.rml.ttl";
File file = new File(TestCarml.class.getResource(fileName).getFile());
// Or just set the basepath if you know it.
// Note that the basepath doesn't have to be set if logical source 
// described in the mapping uses an absolute file path to the source.
String basePathUrl = file.getParent();
System.out.println(basePathUrl);

// Create mapper with specific basepath for logical sources.
Path basePath = Paths.get(basePathUrl);
RmlMapper mapper = RmlMapper.newBuilder().fileResolver(basePath).build();

// Get mapping file from same folder
Set<TriplesMap> mapping =
	RmlMappingLoader
		.build()
		.load(Paths.get(basePathUrl + "/parentTriplesMapping.rml.ttl"), RDFFormat.TURTLE);

// Execute mapping
Model result = mapper.map(mapping);

// Print model
result.forEach(System.out::println);
Binding the input stream is not necessary in this case since we're using a file based source. Binding inputstreams is useful when you don't have a file, but some other process has a stream of data it wants to process.
I'll make a note to add some more examples and explanation to the readme about this.
I hope this helps. If I misintepreted your question please let me know.
Cheers,

Pano

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/carml/carml","title":"carml/carml","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/carml/carml"}},"updates":{"snippets":[{"icon":"PERSON","message":"@pmaria in #18: Hi Adam,\r\n\r\nFirst off, thanks for trying out CARML!\r\n\r\nI'm sorry that you're having trouble with the API. Understandable as well, since our documentation is not yet up to par. We're working on it!\r\n\r\nFrom your description I'm not entirely sure what you want to achieve. I believe you're trying to execute the mapper on the `parentTriplesMapping.rml.ttl` file in the tests as is.\r\n\r\nIn that case you could do something like:\r\n```java\r\n// Determine base path url string for a classpath resource\r\nString fileName = \"parentTriplesMapping.rml.ttl\";\r\nFile file = new File(TestCarml.class.getResource(fileName).getFile());\r\n// Or just set the basepath if you know it.\r\n// Note that the basepath doesn't have to be set if logical source \r\n// described in the mapping uses an absolute file path to the source.\r\nString basePathUrl = file.getParent();\r\nSystem.out.println(basePathUrl);\r\n\r\n// Create mapper with specific basepath for logical sources.\r\nPath basePath = Paths.get(basePathUrl);\r\nRmlMapper mapper = RmlMapper.newBuilder().fileResolver(basePath).build();\r\n\r\n// Get mapping file from same folder\r\nSet\u003cTriplesMap\u003e mapping =\r\n\tRmlMappingLoader\r\n\t\t.build()\r\n\t\t.load(Paths.get(basePathUrl + \"/parentTriplesMapping.rml.ttl\"), RDFFormat.TURTLE);\r\n\r\n// Execute mapping\r\nModel result = mapper.map(mapping);\r\n\r\n// Print model\r\nresult.forEach(System.out::println);\r\n```\r\n\r\nBinding the input stream is not necessary in this case since we're using a file based source. Binding inputstreams is useful when you don't have a file, but some other process has a stream of data it wants to process.\r\n\r\nI'll make a note to add some more examples and explanation to the readme about this.\r\n\r\nI hope this helps. If I misintepreted your question please let me know.\r\n\r\nCheers,\r\nPano"}],"action":{"name":"View Issue","url":"https://github.com/carml/carml/issues/18#issuecomment-339006118"}}}

**Comment by pmaria** [comment] 2017-10-25 07:22
Hi @asotona,

Ok so you do want to use a json input stream as the source.

In that case you can update the mapping like so:
```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ex: <http://example.com/>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .
@prefix carml: <http://carml.taxonic.com/carml/> .

<#ParentTriplesMapping> a rr:TriplesMap;
	rml:logicalSource [
		rml:source [
			a carml:Stream ;
		];
		rml:referenceFormulation ql:JSONPath;
		rml:iterator "$.colors"
	];

	rr:subjectMap [
		rr:template "http://example.com/Color/{color}";
		rr:class ex:Color
	];
	
	rr:predicateObjectMap [
		rr:predicate ex:hasCode;
		rr:objectMap [
			rr:parentTriplesMap <#ColorCode>;
		];
	].
	
<#ColorCode> a rr:ParentTriplesMap;
	rml:logicalSource [
		rml:source [
			a carml:Stream ;
		];
		rml:referenceFormulation ql:JSONPath;
		rml:iterator "$.colors"
	];
	
	rr:subjectMap [
		rr:template "http://example.com/ColorCode/{code.rgba[0]},{code.rgba[1]},{code.rgba[2]},{code.rgba[3]}";
		#rml:reference "hex";
		rr:class ex:RGBA
	].
```

And execute the mapping like so:
```java
// Get the JSON input stream from somewhere
InputStream inputStream = getJsonInputStream("parentTriplesTestInput.json");

// Create mapper and bind stream
RmlMapper mapper = RmlMapper.newBuilder().build();
mapper.bindInputStream(inputStream);

// Get mapping file
Set<TriplesMap> mapping =
	RmlMappingLoader
		.build()
		.load(Paths.get(basePath + "parentTriplesMapping.stream.rml.ttl"), RDFFormat.TURTLE);

// Execute mapping
Model result = mapper.map(mapping);

// Print model
result.forEach(System.out::println);
```

**Comment by asotona** [comment] 2017-10-25 11:15
OK, I see you've unified both iterators to "$.colors" - that works for nested single objects.

However how would you iterate over nested array - when (as I understand) you are limited to the same iterator pattern for all Parent/Child mappings?

**Comment by asotona** [comment] 2017-10-25 11:43
I see following mapping is passing your tests:
```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ex: <http://example.com/>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix xsd: <http://www.w3.org/2001/XMLSchema#> .

<#ParentTriplesMapping> a rr:TriplesMap;
	rml:logicalSource [
    	rml:source "parentTriplesTestInput.json";
    	rml:referenceFormulation ql:JSONPath;
    	rml:iterator "$.colors"
  	];

  	rr:subjectMap [
    	rr:template "http://example.com/Color/{color}";
    	rr:class ex:Color
  	];
  	
	rr:predicateObjectMap [
		rr:predicate ex:hasCode;
		rr:objectMap [
			rr:parentTriplesMap <#ColorCode>;
		];
	].
	
<#ColorCode> a rr:ParentTriplesMap;
	rml:logicalSource [
		rml:source "parentTriplesTestInput.json";
		rml:referenceFormulation ql:JSONPath;
		rml:iterator "$.colors.code";
	];
	
	rr:subjectMap [
		rr:template "http://example.com/ColorCode/{rgba[0]},{rgba[1]},{rgba[2]}, {rgba[3]}";
		rr:class ex:RGBA
	].
```

Does it mean the processing logic of the rml:iterator depends on the source stream origin?

Thanks,
Adam

**Comment by pmaria** [comment] 2017-10-25 16:12
Hi Adam,

That test only tests the loading of that mapping file using the  RdfMapper, not actually executing it. It's not a correct mapping, and this is misleading. We should fix this in #5. Thanks for pointing that out, and sorry for causing confusion.

The way you would handle different logical sources is bij using a join as per http://rml.io/spec.html#logical-join.

An example of this can be found in the `com.taxonic.carml.engine.iotests.RefObjectMapperTest` class.

e.g.
```
@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#>.
@prefix ex: <http://example.com/ns#>.
@prefix xsd: <http://www.w3.org/2001/XMLSchema#>.
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#>.

<#JoinIntegratedMappingD2>
rml:logicalSource [
	rml:source "joinMultipleBreakfasts.json" ;
	rml:referenceFormulation ql:JSONPath ;
	rml:iterator "$.food"
];
rr:subjectMap [
	rr:template "http://food.example.com/{name}";
	rr:class ex:breakfastItem ;
];

rr:predicateObjectMap [
	rr:predicate ex:originatesFrom;
	rr:objectMap [
		rr:parentTriplesMap <#CountryMapping>;
		rr:joinCondition [
			rr:child "countryOfOrigin";
			rr:parent "name" ] 
		]
	].

 <#CountryMapping>
	rml:logicalSource [
		rml:source "joinMultipleCountries.json";
		rml:referenceFormulation ql:JSONPath;
		rml:iterator "$.country"
		];
		
		rr:subjectMap [
			rr:template "http://country.example.com/{name}";
			rr:class ex:Country ;
		];
		
		rr:predicateObjectMap [
			rr:predicate ex:officialLanguage;
			rr:objectMap [
				rml:reference "officialLanguage"]
		] .
```

**Comment by pmaria** [comment] 2018-02-23 11:18
@asotona Did you manage to get it working the way you wanted?
If yes, could you please close this issue?
If no, can we help you further?

**Comment by asotona** [comment] 2018-02-27 08:49
Hi Pano,
unfortunately I didn't manage to get it working. The root cause is in inability of the JSONPath to traverse to "parent" node. Maybe you can help me, however I don't see a way to use CARML (and also any other RML utilising JSONPath) to map JSON with nested arrays into RDF.

**Comment by pmaria** [comment] 2018-03-02 10:38
Hi @asotona, closing this and opening a new issue.

**Comment by mdavino** [comment] 2018-03-20 09:43
Hi, i get "java.lang.RuntimeException: Logical sources are not equal"
this is my case:



@prefix rr: <http://www.w3.org/ns/r2rml#>.
@prefix rml: <http://semweb.mmlab.be/ns/rml#>.
@prefix ex: <http://example.com/>.
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix carml: <http://carml.taxonic.com/carml/> .

<#OA> 	rml:logicalSource [
		rml:source [
			a carml:Stream;
			carml:streamName "stream-A";
		];
		rml:referenceFormulation ql:JSONPath;
		rml:iterator "$"
	];
	rr:subjectMap [
		rr:template "http://example.com/OA/{CD-CODICI.ESC}{CD-CODICI.ECP}";
		rr:class ex:OA
	] . 

 <#SchedaICCD> 	rml:logicalSource [
		rml:source [
			a carml:Stream;
			carml:streamName "stream-A";
		];
		rml:referenceFormulation ql:JSONPath;
		rml:iterator "$"
	];
	rr:subjectMap [
		rr:template "http://example.com/SchedaICCD/{CD-CODICI.ESC}{CD-CODICI.ECP}";
		rr:class ex:SchedaICCD
	];
	rr:predicateObjectMap [
		rr:predicate ex:cataloga;
		rr:objectMap [
			rr:parentTriplesMap  <#OA>;
		] ;
	] .	
	

===================
{
     "tipooggetto": "prova",
     "CD-CODICI": {
              "TSK": "OA",
              "LIR": "C",
              "ESC": "S83",
              "ECP": "UNISADIP2"
       }
}


===========
...
 mapper.bindInputStream("stream-A", inputStream);
....
Set<TriplesMap> mapping =
				RmlMappingLoader
					.build()
					.load(mappingStream, RDFFormat.TURTLE);

Model result = mapper.map(mapping);


============

Can you help me? thks

**Comment by pmaria** [comment] 2018-03-20 19:49
Hi @mdavino,

Thanks for posting.

This is indeed unintended behavior. It seems we introduced a bug in the last release. We'll look into it.

In the mean time, declaring the logical source and reusing it does work properly.

```
@prefix rr: <http://www.w3.org/ns/r2rml#> .
@prefix rml: <http://semweb.mmlab.be/ns/rml#> .
@prefix ex: <http://example.com/> .
@prefix ql: <http://semweb.mmlab.be/ns/ql#> .
@prefix carml: <http://carml.taxonic.com/carml/> .

<#LS>
  rml:source [
    a carml:Stream;
    carml:streamName "stream-A";
  ];
  rml:referenceFormulation ql:JSONPath;
  rml:iterator "$"
.

<#OA> 
  rml:logicalSource <#LS> ;
  rr:subjectMap [
    rr:template "http://example.com/OA/{CD-CODICI.ESC}{CD-CODICI.ECP}";
    rr:class ex:OA
  ] .

<#SchedaICCD> 
  rml:logicalSource <#LS> ;
  rr:subjectMap [
    rr:template "http://example.com/SchedaICCD/{CD-CODICI.ESC}{CD-CODICI.ECP}";
    rr:class ex:SchedaICCD
  ] ;
  rr:predicateObjectMap [
    rr:predicate ex:cataloga;
      rr:objectMap [
        rr:parentTriplesMap <#OA>;
      ] ;
  ] .
```

**Comment by pmaria** [comment] 2018-07-31 15:19
Was fixed in last release

**Closed by pmaria** 2018-07-31 15:19 UTC
Labels: bug
