### ISSUE TITLE
CLI interface

### ISSUE THREAD

**Issue by ktk** [carml/carml#38] opened 2018-03-15 19:58 UTC
Hi,

Mainly an issue to tell you that I watch the space, very interesting project! I use RML for quite a long time but implementations are so far... uhm, questionable.

Carml looks great, I see cli-interface is on the todos. Do you have any ETA for that?

**Comment by pmaria** [comment] 2018-03-18 15:27
Hi @ktk,

Thanks! We're trying to make CARML useful for more implementations. We're not there yet, but working on it :).

The CLI is indeed on the roadmap. Can't say for sure when we'll get around to it. There are a couple of things that have higher priority. For example improving the logging.

In the mean time I played around with creating a CLI a while back over at https://github.com/pmaria/carml-jar.
It's pretty bare bones, and the function loading is questionable, but it works ok. I'll update the CARML version on that end.

**Comment by ktk** [comment] 2018-10-29 17:02
We now have one here: https://github.com/netage/carml-cli

**Comment by pmaria** [comment] 2022-07-18 09:02
@semanticfire I recently started setting up a [separate repo](https://github.com/carml/carml-jar/settings) for a new CLI implementation based on the updated API, and was meaning to get into contact with you guys about it once it was somewhat shareable. Would be great to collaborate on it. Shall we plan a call to discuss?

**Comment by semanticfire** [comment] 2022-07-18 09:11
> @semanticfire I recently started setting up a [separate repo](https://github.com/carml/carml-jar) for a new CLI implementation based on the updated API, and was meaning to get into contact with you guys about it once it was somewhat shareable. Would be great to collaborate on it. Shall we plan a call to discuss?

you know how to reach me

**Comment by semanticfire** [comment] 2022-07-21 15:21
I called @pmaria today,  @tobiasscweizer please try the https://github.com/carml/carml-jar repo to see if that works for you

**Comment by tobiasschweizer** [comment] 2022-07-21 16:42
> I called @pmaria today, @tobiasschweizer please try the https://github.com/carml/carml-jar repo to see if that works for you

That sounds great! I'll try that asap and give you feedback.

**Comment by tobiasschweizer** [comment] 2022-07-21 17:15
Ok, I cloned the repo and ran `mvn clean package` but ran into errors. 

My setup on macOS:

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: .../maven/3.8.6/libexec
Java version: 18.0.1.1, vendor: Homebrew, runtime: .../openjdk/18.0.1.1/libexec/openjdk.jdk/Contents/Home
Default locale: en_CH, platform encoding: UTF-8

openjdk 11.0.12 2021-07-20
OpenJDK Runtime Environment Homebrew (build 11.0.12+0)
OpenJDK 64-Bit Server VM Homebrew (build 11.0.12+0, mixed mode)

I installed both maven and java with brew. I noticed that maven uses version 18 while java is version 11. Not sure if that could lead to problems. Please let me know if more information is needed.

> [INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.628 s - in io.carml.runner.CarmlMapCommandTest
[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   PathResolverTest.givenPathToDir_whenResolvePaths_thenReturnAllFilePathsInDir:45 
Expected: iterable containing [<src/test/resources/io/carml/runner/input/path-resolver/dir-1/dir-1-1/file-1-1-1>, <src/test/resources/io/carml/runner/input/path-resolver/dir-1/file-1-1>, <src/test/resources/io/carml/runner/input/path-resolver/dir-2/file-2-1>]
     but: item 0: was <src/test/resources/io/carml/runner/input/path-resolver/dir-2/file-2-1>
[ERROR]   Rdf4jModelResolverTest.givenDirectoryWithFilesOfSupportedAndUnsupportedFormats_whenLoadModelWithNoFormat_thenThrowException:111 
Expected: is "Exception occurred while parsing src/test/resources/io/carml/runner/input/rdf4j-model-resolver/rml-2/foo/test-1.rml.foo"
     but: was "Exception occurred while parsing src/test/resources/io/carml/runner/input/rdf4j-model-resolver/rml-2/ttl/test-1.rml.ttl"
[INFO] 
[ERROR] Tests run: 16, Failures: 2, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for carml-jar 1.0.0-SNAPSHOT:
[INFO] 
[INFO] carml-jar .......................................... SUCCESS [  2.488 s]
[INFO] carml-runner ....................................... FAILURE [ 18.497 s]
[INFO] carml-output ....................................... SKIPPED
[INFO] carml-output-rdf4j ................................. SKIPPED
[INFO] carml-app .......................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.258 s
[INFO] Finished at: 2022-07-21T19:04:53+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.0.0-M7:test (default-test) on project carml-runner: There are test failures.
[ERROR] 
[ERROR] Please refer to .../carml-jar/carml-runner/target/surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :carml-runner

Here are the reports from surefire:

> -------------------------------------------------------------------------------
Test set: io.carml.runner.input.PathResolverTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.135 s <<< FAILURE! - in io.carml.runner.input.PathResolverTest
io.carml.runner.input.PathResolverTest.givenPathToDir_whenResolvePaths_thenReturnAllFilePathsInDir  Time elapsed: 0.02 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: iterable containing [<src/test/resources/io/carml/runner/input/path-resolver/dir-1/dir-1-1/file-1-1-1>, <src/test/resources/io/carml/runner/input/path-resolver/dir-1/file-1-1>, <src/test/resources/io/carml/runner/input/path-resolver/dir-2/file-2-1>]
     but: item 0: was <src/test/resources/io/carml/runner/input/path-resolver/dir-2/file-2-1>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.carml.runner.input.PathResolverTest.givenPathToDir_whenResolvePaths_thenReturnAllFilePathsInDir(PathResolverTest.java:45)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

> -------------------------------------------------------------------------------
Test set: io.carml.runner.input.Rdf4jModelResolverTest
-------------------------------------------------------------------------------
Tests run: 7, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.507 s <<< FAILURE! - in io.carml.runner.input.Rdf4jModelResolverTest
io.carml.runner.input.Rdf4jModelResolverTest.givenDirectoryWithFilesOfSupportedAndUnsupportedFormats_whenLoadModelWithNoFormat_thenThrowException  Time elapsed: 0.004 s  <<< FAILURE!
java.lang.AssertionError: 

Expected: is "Exception occurred while parsing src/test/resources/io/carml/runner/input/rdf4j-model-resolver/rml-2/foo/test-1.rml.foo"
     but: was "Exception occurred while parsing src/test/resources/io/carml/runner/input/rdf4j-model-resolver/rml-2/ttl/test-1.rml.ttl"
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at io.carml.runner.input.Rdf4jModelResolverTest.givenDirectoryWithFilesOfSupportedAndUnsupportedFormats_whenLoadModelWithNoFormat_thenThrowException(Rdf4jModelResolverTest.java:111)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.apache.maven.surefire.junitplatform.LazyLauncher.execute(LazyLauncher.java:55)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.execute(JUnitPlatformProvider.java:223)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:175)
	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:139)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:456)
	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:169)
	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:595)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:581)

**Comment by tobiasschweizer** [comment] 2022-07-21 17:24
ok, I set my JAVA_HOME accordingly, now `mvn` uses Java version: 11.0.12 as well, but the problem is still there

**Comment by pmaria** [comment] 2022-07-21 17:53
@tobiasschweizer seems to be a problem with the ordering of the way files are read. I pushed a possible fix. Let me know if that helps. Otherwise please open a new issue on the project so we can track it.

**Comment by tobiasschweizer** [comment] 2022-07-22 06:19
> @tobiasschweizer seems to be a problem with the ordering of the way files are read. I pushed a possible fix. Let me know if that helps. Otherwise please open a new issue on the project so we can track it.

@pmaria Great, thanks for the fix.

I confirm that I can now build the jar and run it. :-)

For running it, I have to use the `map` command, e.g., `java -jar carml-jar-1.0.0-SNAPSHOT-0.4.1.jar map -m mapping.ttl -r inputdir` and there is still some logging to stdout. I assume you are still working on this, right? Otherwise I can create an issue on the CLI repo with the complete output.

I also have some questions about the command line options. Maybe it would be good to discuss this on the CLI repo as well?

In any case that looks quite good! Thanks for this!

**Comment by tobiasschweizer** [comment] 2022-07-22 06:33
I have just tried the CLI version with the data that caused the null pointer exception prior to version 0.4.1. It works smoothly now!

**Comment by pmaria** [comment] 2022-07-22 06:37
> I confirm that I can now build the jar and run it. :-)

Great!
 
> For running it, I have to use the `map` command, e.g., `java -jar carml-jar-1.0.0-SNAPSHOT-0.4.1.jar map -m mapping.ttl -r inputdir` and there is still some logging to stdout. I assume you are still working on this, right? Otherwise I can create an issue on the CLI repo with the complete output.

Yep, that still needs work. Mapping to exit codes and such. Feel free to open issues for any missing or incomplete features.

> I also have some questions about the command line options. Maybe it would be good to discuss this on the CLI repo as well?

Yes, best to discuss there.

> In any case that looks quite good! Thanks for this!

Cool!

**Comment by ktk** [comment] 2022-11-12 13:51
I think we can close this one here? Thanks for the work!

**Comment by pmaria** [comment] 2022-11-13 10:49
Yeah, I'll close this as soon as I've updated the readme with a section linking to the carml-jar repo. It still needs a bit of documentation etc. but is already in a useable state.

**Comment by tobiasschweizer** [comment] 2022-11-14 06:48
> It still needs a bit of documentation etc. but is already in a useable state.

I can confirm that: I used it and it does the job nicely :-) Does the CLI version actually already support stdin (CARML stream)?

**Comment by pmaria** [comment] 2022-11-14 07:07
> I can confirm that: I used it and it does the job nicely :-) 

Great!

> Does the CLI version actually already support stdin (CARML stream)?

Ah no, l'll open an issue for that.

**Comment by tobiasschweizer** [comment] 2022-11-14 07:08
That' great, thanks.

**Comment by ktk** [comment] 2022-11-14 07:50
@pmaria that just reminds me that @semanticfire implemented [carml-service](https://github.com/zazuko/carml-service/), this is what we use when we convert the 50M XML documents I mentioned. Like this we can parallelize it and scale it out on Kubernetes & it gets called in one of our [barnard59](https://github.com/zazuko/barnard59) pipelines.

In case you want to mention that in the readme let me know, I can do a pull request or provide a sentence about it.

**Comment by pmaria** [comment] 2022-11-14 07:53
Yes great!

**Closed** 2023-03-06 09:53 UTC
